// Types are now generated by Convex from the schema (convex/schema.ts).
// Import types from Convex when needed:
//   import type { Doc, Id } from "../../convex/_generated/dataModel";
//   Doc<"decks"> = a deck document
//   Doc<"cards"> = a card document
//   Id<"decks"> = a deck ID
//   Id<"cards"> = a card ID

export type DeckStats = {
    cardCount: number;
    lastStudied?: number;
}
